Story4
iO-Academy/2024-mar-sde-quizzer-api-pandamonium pull request #4
Opened 2024-06-12 13:25 UTC by Richtbiscuitcoder

https://trello.com/c/Y8mTOpYT/71-story-4-add-new-questions

please review our code :)

2024-06-12 13:43 UTC, mallowmew requested changes

2024-06-12 13:43 UTC, mallowmew commented on routes/api.php
> +Route::post('/questions', [QuizAPIController::class, 'addNewQuestion']);
Do requests to the `/questions` route go in the Quiz controller?

2024-06-12 13:43 UTC, mallowmew commented on tests/Feature/QuizTest.php
> +    public function test_addNewQuestion_questionValidation(): void
```suggestion
    public function test_addNewQuestion_missingQuestion(): void
```

2024-06-12 13:43 UTC, mallowmew commented on tests/Feature/QuizTest.php
> +    public function test_addNewQuestion_pointsValidation(): void
```suggestion
    public function test_addNewQuestion_missingPoints(): void
```

2024-06-12 13:57 UTC, mallowmew requested changes

2024-06-12 13:57 UTC, mallowmew commented on tests/Feature/QuizTest.php
Can you think of a test case that would cause a failure to save into the database?

2024-06-12 14:19 UTC, mallowmew commented on app/Http/Controllers/QuestionAPIController.php
> +            'points' => 'required|integer',
Is 0 points acceptable? -2 points?

2024-06-12 14:38 UTC, Richtbiscuitcoder commented on tests/Feature/QuizTest.php
no..

2024-06-12 14:56 UTC, mallowmew approved these changes

2024-06-12 15:07 UTC, mallowmew requested changes

2024-06-12 15:07 UTC, mallowmew commented on app/Http/Controllers/QuestionAPIController.php
> +            'points' => 'required|min:1|integer',
what if you try to add a question for a quiz that doesn't exist?

2024-06-13 08:02 UTC, mallowmew approved these changes

2024-06-13 08:16 UTC, merged